services:
  qashio-api:
    build: 
      context: ./qashio-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/qashio_points
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - default

  qashio-frontend:
    build: 
      context: ./qashio-frontend-assignment
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
    depends_on:
      - qashio-api
    networks:
      - default

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=qashio_points
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - default

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:

networks:
  default:
    driver: bridge